version: '{build}'

environment:
  version: 0.1.0
  suffix: -dev001
  COVERALLS_REPO_TOKEN:
    secure: KzTaRAfwaHgRAc7rfLWCYjHQocbDbCOm/bbwxMCxJMgSahcCzTjPfzTs+aHOnzsv

install:
- ps: |
    Write-Host "Commit being built = $($Env:APPVEYOR_REPO_COMMIT)"
    Write-Host "Current build version = $($Env:VERSION)"
    Write-Host "Target branch = $($Env:APPVEYOR_REPO_BRANCH)"
    If ($Env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null)
    {
      Write-Host "Pull Request = $($Env:APPVEYOR_PULL_REQUEST_NUMBER)"
    }
    $Env:FILE_VERSION = "$($Env:VERSION).$($Env:APPVEYOR_BUILD_NUMBER)"
    $Env:FULL_VERSION = "$($Env:VERSION)$($Env:SUFFIX)"
    Write-Host "File Version = $($Env:FILE_VERSION)"
    Write-Host "Full Version = $($Env:FULL_VERSION)"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(VERSION)'
  assembly_file_version: '$(VERSION)'
  assembly_informational_version: '$(FULL_VERSION)'

configuration: Release

platform: Any CPU

before_build:
- .\nuget\nuget.exe restore "%APPVEYOR_PROJECT_NAME%.sln"

build:
  verbosity: minimal
  project: '$(APPVEYOR_PROJECT_NAME).sln'

after_build:
- .\nuget\nuget.exe pack "source\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -IncludeReferencedProjects

test_script:
- packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"nunit-console.exe" -targetargs:"/noshadow /domain:single tests\%APPVEYOR_PROJECT_NAME%.Tests\bin\Release\%APPVEYOR_PROJECT_NAME%.Tests.dll" -output:coverage.xml

after_test: 
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

artifacts:
- path: '$(APPVEYOR_PROJECT_NAME)*.nupkg'
  name: NuGet Package
- path: 'coverage.xml'
  name: Coverage Data
